services:
  - type: cron
    name: interpark-monitor
    runtime: python
    schedule: "*/5 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
